// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

//randomRPM()

void updateValue(lv_event_t * e)
{
  lv_label_set_text(ui_RPMtext, "3000");
	// Your code here
}
