// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_orangeBG);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_orangeBG);

    ui_RPM = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_RPM, 230);
    lv_obj_set_height(ui_RPM, 230);
    lv_obj_set_x(ui_RPM, -1);
    lv_obj_set_y(ui_RPM, 0);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RPM, 0, 8000);
    lv_arc_set_value(ui_RPM, 5000);
    ui_object_set_themeable_style_property(ui_RPM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_orangeBG);
    ui_object_set_themeable_style_property(ui_RPM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_orangeBG);
    ui_object_set_themeable_style_property(ui_RPM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_orangeMG);
    ui_object_set_themeable_style_property(ui_RPM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_orangeMG);

    ui_object_set_themeable_style_property(ui_RPM, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_orangeFG);
    ui_object_set_themeable_style_property(ui_RPM, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_orangeFG);

    lv_obj_set_style_bg_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RPM, lv_color_hex(0xDB1212), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RPMtext = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMtext, 1);
    lv_obj_set_y(ui_RPMtext, 89);
    lv_obj_set_align(ui_RPMtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMtext, "1500");
    lv_obj_set_style_text_font(ui_RPMtext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // this component is out of sight. Just in case I need a new one or saved as a template. 
    /*
    ui_RPMlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMlabel, -96);
    lv_obj_set_y(ui_RPMlabel, 103);
    lv_obj_set_align(ui_RPMlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMlabel, "RPM");
    */

    ui_TEMPlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEMPlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPlabel, 0);
    lv_obj_set_y(ui_TEMPlabel, -22);
    lv_obj_set_align(ui_TEMPlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPlabel, "17C");
    lv_obj_set_style_text_font(ui_TEMPlabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOLTlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VOLTlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOLTlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOLTlabel, -4);
    lv_obj_set_y(ui_VOLTlabel, 16);
    lv_obj_set_align(ui_VOLTlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOLTlabel, "13v");
    lv_obj_set_style_text_font(ui_VOLTlabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label0 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label0, -68);
    lv_obj_set_y(ui_Label0, 70);
    lv_obj_set_align(ui_Label0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label0, "0");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -97);
    lv_obj_set_y(ui_Label1, 22);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "1");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -89);
    lv_obj_set_y(ui_Label2, -36);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "2");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -53);
    lv_obj_set_y(ui_Label3, -79);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "3");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -96);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "4");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 51);
    lv_obj_set_y(ui_Label5, -79);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "5");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 87);
    lv_obj_set_y(ui_Label6, -36);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "6");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 94);
    lv_obj_set_y(ui_Label7, 22);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "7");

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 64);
    lv_obj_set_y(ui_Label8, 70);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "8");

    // evento que no ncesito. lo dejo como plantilla por si acaso mas adelante neeito uno.
    //lv_obj_add_event_cb(ui_RPM, ui_event_RPM, LV_EVENT_ALL, NULL);

}
